name: Auto Fix Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  auto-fix-format:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format on source files
        run: |
          FILES=$(find . -regex '.*\.\(cpp\|hpp\|c\|h\)' -type f)
          for file in $FILES; do
            clang-format -style=Google -i "$file"
          done

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: auto format using clang-format"
          branch: main
          push_options: --force
